name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ensemble.carnal.cloud
          username: debian
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd Elections-Backend/
            git pull
            swift build -c release
            sudo supervisorctl restart ElectionsSvr
